version: "3.9"

services:
  backend:
    build: .
    container_name: django-drf
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - 8000:8000
    volumes:
     - .:/core
    depends_on:
      - redis

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: web
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  worker:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/core
    depends_on:
      - redis
      - backend
  beat:
    build: .
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/core
    depends_on:
      - redis
      - db
      - backend


volumes:
  smtp4dev-data:
  postgres_data: