version: "3.9"

services:
  backend:
    build: .
    container_name: django-drf
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - 8000:8000
    volumes:
     - .:/core
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://django-drf:8000
  
  worker:
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  smtp4dev-data: