# Generated by Django 5.1.1 on 2024-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='video',
            field=models.TextField(),
        ),
    ]
