# Generated by Django 5.1.1 on 2024-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_properties_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='video',
        ),
        migrations.AddField(
            model_name='properties',
            name='video_div',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='video_style',
            field=models.TextField(default=''),
        ),
    ]
