# Generated by Django 5.1.1 on 2024-11-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_properties_video_properties_video_div_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='video_div',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='video_style',
        ),
    ]
