# Generated by Django 5.1.1 on 2024-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_video_div_properties_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='map',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='video',
            field=models.CharField(max_length=220),
        ),
    ]
