# Generated by Django 4.2 on 2025-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='facebook',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AlterField(
            model_name='agents',
            name='instagram',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AlterField(
            model_name='agents',
            name='linkedin',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AlterField(
            model_name='agents',
            name='twitter',
            field=models.CharField(default='#', max_length=220),
        ),
    ]
